name: "Theron Studios"
permalink: pretty
author: Theron Studios
email: hello@theronstudios.com
url: http://theronstudios.com
markdown: kramdown

exclude: ["CNAME","editorconfig.txt","Gemfile","Gemfile.lock","README.md", "RAKEFILE"]

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  js_compressor: uglifier
  css_compressor: sass

navigation:
- text: About
  url: /about/
- text: Process
  url: /process/
- text: Work
  url: /work/
- text: Blog
  url: /blog/
- text: Contact
  url: /contact/
